### PR TITLE
fix: remove type imports from "http" for Deno compatibility

### LINKED ISSUE #218: Cannot be imported by Deno
**What happened?**

see https://github.com/octokit/octokit.js/issues/24#issuecomment-817361886

**What the problem might be**

We have to remove the type imports from node's `"http"` package.

compare the change at https://github.com/octokit/webhooks.js/pull/518/commits/662f35c35ce7b747707eb44337b96d7f404fa21d

### PR DESCRIPTION
**Pull request by laughedelic**
Fixes #218.

### CODE REVIEW

File: src/middleware/node/parse-request.ts [hunk 1]
```diff
@@ -41,7 +44,7 @@ export async function parseRequest(
     let bodyChunks: Uint8Array[] = [];
     request
       .on("error", reject)
-      .on("data", (chunk) => bodyChunks.push(chunk))
+      .on("data", (chunk: any) => bodyChunks.push(chunk))
```
Comment (laughedelic) [inline src/middleware/node/parse-request.ts:47]: Should this be 
```suggestion
      .on("data", (chunk: Uint8Array) => bodyChunks.push(chunk))
```

instead?

**Review by gr2m — APPROVED** [review]
Thanks a lot 💐🦕
